name: Open Source Compliance
on:
  push:
  pull_request:
  schedule: [{ cron: '17 2 * * *' }]
  workflow_dispatch:
permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  pull-requests: read
  statuses: write
jobs:
  run:
    uses: itsapdemo/open-source-kit/.github/workflows/repo-compliance.yml@main
    secrets: inherit
